### ISSUE TITLE
Implement org.freedesktop.DBus.Properties

### ISSUE THREAD

**Issue by hxss** [altdesktop/python-dbus-next#49]
Hello. Thanks for great work.
I'm using your lib to write mpris player. When I run it I receive error:
```
ERROR:root:got unexpected error processing a message: could not find an interface "org.freedesktop.DBus.Properties" at path: "/org/mpris/MediaPlayer2"
```
Despite this dbus-next successfully implements all methods of `Properties` interface. And I can see `org.freedesktop.DBus.Properties` interface on my player in d-feet.  What this error mean?
If I try to manualy export `Properties` interface d-feet shows 2 instances of it and the error disappears.

**Comment by acrisci** [comment]
I have pretty thoroughly tested the properties interfaces and I think they work correctly. Can you provide more info on what you are doing so I can track this down? Code samples would be helpful.

**Comment by hxss** [comment]
here is my fakeplayer(2 small interfaces):
https://gitlab.com/hxss/mpris-fakeplayer/-/blob/master/mpris_fakeplayer/__init__.py

**Comment by acrisci** [comment]
D-feet calls `GetAll` on the properties interface itself which has no properties. From the spec:

> If org.freedesktop.DBus.Properties.GetAll is called with a valid interface name which contains no properties, an empty array should be returned.

We only check for the existence of exported interfaces in the properties handler.

https://github.com/altdesktop/python-dbus-next/blob/f89c1ce1affc0e2d3209d9f0b7e40acbc66cd617/dbus_next/message_bus.py#L748

Practically this is not a problem since no standard interface specifies any properties, so these calls are never useful. And d-feet does actually do the right thing in any case. But this technically is a spec violation and could be fixed.

Another issue is that this error should not be logged with error level since this is an expected client error. This could be fixed as well.

Aside from the logging and the minor spec violation, the properties interface works correctly.
